{
    "name":"system",
    "profiles":[
        "dev"
    ],
    "label":null,
    "version":"92bd1adf4d22d2a27ce34cd0abc7d1702ad8fff6",
    "state":null,
    "propertySources":[
        {
            "name":"https://github.com/intomylife/SpringCloud/springcloud-config-git/config-repo/system-dev.properties",
            "source":{
                "hello":"I'm dev."
            }
        }
    ]
}
